kind: Namespace
apiVersion: v1
metadata:
  name: titanic
  
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: titanic
type: Opaque
stringData:
  user: python-app
  password: 1f2d1e2e67df
  master: SGvbjpSmBknvjLLzKmxKaHND
  
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: api-variables
  namespace: titanic
data:
  database: titanic
  reads: mysql-read.titanic.svc.cluster.local
  writes: mysql-0.mysql.titanic.svc.cluster.local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: titanic
  labels:
    app: mysql
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log-bin
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    super-read-only
